from typing import Protocol
from PIL.Image import Image
import numpy.typing as npt


class Material(Protocol):
    @staticmethod
    def get_fragment() -> str: ...
    @staticmethod
    def get_data_size() -> int: ...
    @staticmethod
    def get_texture_count() -> int: ...
    @staticmethod
    def get_texture_size() -> tuple[int, int]: ...
    def get_data(self) -> npt.NDArray: ...
    def get_textures(self) -> list[Image]: ...
